import assert from 'node:assert/strict';import{createRequire}from'node:module';const{chromium}=createRequire(import.meta.url)('playwright');
const browser=await chromium.launch({channel:'chrome',headless:true});
try{const page=await browser.newPage({viewport:{width:1400,height:900}}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto((process.env.SKECHU_TEST_URL||'http://127.0.0.1:18782/')+'?storage=dense-group-test-'+Date.now());await page.waitForFunction(()=>workspaceReady);
 const result=await page.evaluate(()=>{const seed=Array.from({length:1200},(_,i)=>({id:'dense-'+i,name:'色塊 '+i,type:'arrow',closed:true,curved:false,autoTraceColored:true,width:0,fill:'#315cad',fillOpacity:1,layerGroup:{id:'dense',name:'大量色塊',collapsed:true},points:Array.from({length:24},(_,j)=>({x:(i%40)*20+8*Math.cos(j*Math.PI/12),y:Math.floor(i/40)*20+8*Math.sin(j*Math.PI/12)}))}));
  const project=makeProject('Dense test',seed,{width:800,height:600});projects=[project];activeProjectId=project.id;activePageId=project.activePageId;items=deepCopy(seed);resetEditorState();applyCanvasSize();renderProjectNav();render();const before=state(),group='group:dense',start=performance.now();selectLayerGroup(group);const selectedMs=performance.now()-start,overlayNodes=selection.querySelectorAll('*').length;const selectedAll=selectedIds.size===1200;
  copyInternalSelection();const copiedAll=internalClipboard.length===1200;
  showLayerMenu({type:'contextmenu',clientX:240,clientY:100,preventDefault(){},stopPropagation(){}},group);const t=performance.now();runLayerAction('delete');const deleteMs=performance.now()-t,deleted=items.length===0;document.getElementById('undo').click();const undoExact=state()===before;document.getElementById('redo').click();const redoExact=items.length===0;document.getElementById('undo').click();setOnlySelected('dense-0');editPoints=true;refreshSelectionUI();const singleHasAnchors=selection.querySelectorAll('circle').length>=24;
  return{selectedMs,deleteMs,overlayNodes,selectedAll,copiedAll,deleted,undoExact,redoExact,singleHasAnchors};});
 assert.ok(result.selectedAll&&result.copiedAll&&result.deleted&&result.undoExact&&result.redoExact&&result.singleHasAnchors);assert.ok(result.overlayNodes<20,'Dense groups cannot create one DOM target per anchor');assert.ok(result.selectedMs<1500&&result.deleteMs<1500,'Dense group operations must remain bounded on this test host');assert.deepEqual(errors,[]);console.log('Dense groups: '+JSON.stringify(result));
}finally{await browser.close()}
