import assert from 'node:assert/strict';
import fs from 'node:fs';
import {createRequire} from 'node:module';
const {chromium}=createRequire(import.meta.url)('playwright');
const browser=await chromium.launch({channel:'chrome',headless:true});
const base=process.env.SKECHU_TEST_URL||'http://127.0.0.1:18782/';
const out='.codex-tmp/image-upscale-ux';fs.mkdirSync(out,{recursive:true});
const source='<svg xmlns="http://www.w3.org/2000/svg" width="640" height="360"><defs><linearGradient id="bg"><stop stop-color="#172b49"/><stop offset="1" stop-color="#325983"/></linearGradient></defs><rect width="640" height="360" fill="url(#bg)"/><path d="M80 255Q130 55 255 135T565 100" stroke="#80ddd0" stroke-width="6" fill="none"/><circle cx="320" cy="180" r="90" fill="#dfbde6"/><path d="M248 180Q270 110 310 155T392 180M255 208Q275 168 314 200T385 204" stroke="#67508f" stroke-width="5" fill="none"/><circle cx="160" cy="140" r="24" fill="#f4b37a"/><circle cx="480" cy="167" r="24" fill="#f4b37a"/><path d="M80 300H560" stroke="#7392ae" stroke-width="2"/><text x="80" y="328" font-family="sans-serif" font-size="16" fill="#ced9ed">Skechu / detail preview</text></svg>';
async function fixture(page,src=source){await page.evaluate(src=>{items=[{id:'hd-ux',type:'image',name:'Detail preview',src:'data:image/svg+xml,'+encodeURIComponent(src),x:0,y:0,w:640,h:360,r:0,opacity:.5,referenceOnly:true,preserveFull:true,locked:false}];setOnlySelected('hd-ux');render();fitView()},src)}
async function open(page){await page.locator('#image-upscale').scrollIntoViewIfNeeded();await page.locator('#image-upscale').click();await page.waitForFunction(()=>!document.getElementById('image-upscale-start').disabled)}
async function ready(page){await page.waitForFunction(()=>document.getElementById('image-upscale-dialog').dataset.ready==='true',null,{timeout:60000})}
async function screenPoint(page,x=.5,y=.5){return page.evaluate(({x,y})=>{const s=document.getElementById('image-upscale-svg'),b=s.viewBox.baseVal,p=new DOMPoint(b.x+b.width*x,b.y+b.height*y).matrixTransform(s.getScreenCTM());return{x:p.x,y:p.y}},{x,y})}
async function primaryVisible(page,id='image-upscale-start'){
 const result=await page.evaluate(id=>{const d=document.getElementById('image-upscale-dialog').getBoundingClientRect(),b=document.getElementById(id).getBoundingClientRect(),f=document.querySelector('#image-upscale-dialog footer').getBoundingClientRect();return{right:d.right-b.right,bottom:d.bottom-b.bottom,inside:b.top>=f.top&&b.bottom<=innerHeight&&b.right<=innerWidth,width:b.width,height:b.height}},id);
 assert.ok(result.inside&&result.right<30&&result.bottom<30&&result.width>=125&&result.height>=40,'Primary button remains bottom-right: '+JSON.stringify(result));
}
try{
 for(const width of [1360,390]){
  const context=await browser.newContext({viewport:{width,height:width===390?844:940},isMobile:width===390,hasTouch:width===390,serviceWorkers:'block'}),page=await context.newPage(),errors=[],heavy=[];
  page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(/tf-4\.22|anime-v3/.test(r.url()))heavy.push(r.url())});
  await page.goto(base+'?mode=web&storage=hd-ux-'+width+'-'+Date.now());await page.waitForFunction(()=>workspaceReady);await fixture(page);const original=await page.evaluate(()=>JSON.stringify(items));await open(page);
  await primaryVisible(page);assert.equal(await page.locator('#image-upscale-handle').isVisible(),false);assert.equal(await page.locator('[data-upscale-mode="split"]').isEnabled(),false);assert.equal(await page.locator('#image-upscale-compare').isEnabled(),false);
  await page.screenshot({path:out+'/before-'+width+'.png'});
  await page.locator('#image-upscale-method').selectOption('resize');await page.locator('#image-upscale-start').click();await ready(page);await primaryVisible(page,'image-upscale-apply');
  await page.locator('#image-upscale-svg').scrollIntoViewIfNeeded();assert.match(await page.locator('#image-upscale-help').textContent(),/整張圖片都已高清/);
  const view=await page.locator('#image-upscale-svg').getAttribute('viewBox'),middle=await screenPoint(page),right=await screenPoint(page,.72);
  if(width===390){const cdp=await context.newCDPSession(page);await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{...middle,id:1}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{...right,id:1}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]})}
  else {await page.mouse.move(middle.x,middle.y);await page.mouse.down();await page.mouse.move(right.x,right.y,{steps:8});await page.mouse.up()}
  assert.ok(Math.abs(Number(await page.locator('#image-upscale-compare').inputValue())-72)<=1,'Drag middle controls split');assert.equal(await page.locator('#image-upscale-svg').getAttribute('viewBox'),view,'Divider drag never pans image');
  const hit=await screenPoint(page,.72,.25),left=await screenPoint(page,.31,.25);await page.mouse.move(hit.x,hit.y);await page.mouse.down();await page.mouse.move(left.x,left.y,{steps:6});await page.mouse.up();assert.ok(Math.abs(Number(await page.locator('#image-upscale-compare').inputValue())-31)<=1,'Entire divider can be dragged');
  await page.locator('#image-upscale-handle').focus();await page.keyboard.press('Home');assert.equal(await page.locator('#image-upscale-compare').inputValue(),'0');await page.keyboard.press('End');assert.equal(await page.locator('#image-upscale-compare').inputValue(),'100');await page.keyboard.press('Shift+ArrowLeft');assert.equal(await page.locator('#image-upscale-compare').inputValue(),'90');assert.equal(await page.evaluate(()=>JSON.stringify(items)),original);
  await page.locator('#image-upscale-center').click();assert.equal(await page.locator('#image-upscale-compare').inputValue(),'50');
  await page.locator('#image-upscale-compare').fill('75');await page.locator('#image-upscale-svg').scrollIntoViewIfNeeded();const resetPoint=await screenPoint(page,.75);await page.mouse.dblclick(resetPoint.x,resetPoint.y);assert.equal(await page.locator('#image-upscale-compare').inputValue(),'50','Double-click returns divider to center');
  await page.locator('[data-upscale-mode="after"]').click();assert.equal(await page.locator('#image-upscale-handle').isVisible(),false);assert.equal(await page.locator('#image-upscale-clip-rect').getAttribute('x'),'0');assert.equal(await page.locator('#image-upscale-before-rect').getAttribute('width'),'0');
  await page.locator('[data-upscale-mode="before"]').click();assert.equal(await page.locator('#image-upscale-clip-rect').getAttribute('width'),'0');await page.locator('[data-upscale-mode="split"]').click();
  await page.locator('#image-upscale-plus').click();await page.locator('#image-upscale-svg').scrollIntoViewIfNeeded();const enlarged=await page.locator('#image-upscale-svg').getAttribute('viewBox'),from=await screenPoint(page,.2,.6),to={x:from.x+25,y:from.y+10};await page.mouse.move(from.x,from.y);await page.mouse.down();await page.mouse.move(to.x,to.y,{steps:5});await page.mouse.up();assert.notEqual(await page.locator('#image-upscale-svg').getAttribute('viewBox'),enlarged,'Drag away from split pans');assert.equal(await page.locator('#image-upscale-compare').inputValue(),'50');
  const handle=await page.locator('#image-upscale-handle').boundingBox();assert.ok(handle.width>=44&&handle.width<52&&handle.height>=48,'Handle stays touch sized after zoom');
  if(width===390){const cdp=await context.newCDPSession(page),a=await screenPoint(page,.28),b=await screenPoint(page,.72);await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{...a,id:1},{...b,id:2}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:a.x-25,y:a.y,id:1},{x:b.x+25,y:b.y,id:2}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});assert.ok(parseInt(await page.locator('#image-upscale-zoom').textContent())>150,'Pinch still zooms')}
  await page.locator('#image-upscale-fit').click();await page.locator('#image-upscale-svg').scrollIntoViewIfNeeded();await page.screenshot({path:out+'/comparison-'+width+'.png'});
  await primaryVisible(page,'image-upscale-apply');await page.locator('.upscale-body').evaluate(el=>el.scrollTop=0);await primaryVisible(page,'image-upscale-apply');
  if(width===390){await page.setViewportSize({width:390,height:667});await primaryVisible(page,'image-upscale-apply');await page.screenshot({path:out+'/short-phone.png'});await page.setViewportSize({width:390,height:844})}
  await page.locator('#image-upscale-close').click();assert.equal(await page.evaluate(()=>JSON.stringify(items)),original);
  // Match the worker's device-dependent cap BEFORE downloading a model or starting a job.
  await fixture(page,source.replace('width="640" height="360"','width="1000" height="600"'));await open(page);await page.locator('#image-upscale-factor').selectOption('4');assert.equal(await page.locator('#image-upscale-start').isEnabled(),width!==390);if(width===390)assert.match(await page.locator('#image-upscale-details').textContent(),/800 萬/);await page.locator('#image-upscale-close').click();
  await page.evaluate(()=>{items=[];clearSelectionState(false);render()});await page.locator('#image-upscale').click();assert.ok(await page.locator('#image-upscale-empty').isVisible());assert.equal(await page.locator('#image-upscale-start').isEnabled(),false);
  await page.evaluate(async()=>{const c=document.createElement('canvas');c.width=60;c.height=40;c.getContext('2d').fillRect(0,0,60,40);const blob=await new Promise(r=>c.toBlob(r,'image/png')),data=new DataTransfer();data.items.add(new File([blob],'Dropped.png',{type:'image/png'}));document.getElementById('image-upscale-preview').dispatchEvent(new DragEvent('drop',{bubbles:true,cancelable:true,dataTransfer:data}))});await page.waitForFunction(()=>!document.getElementById('image-upscale-start').disabled);assert.equal(await page.locator('#image-upscale-empty').isVisible(),false);assert.match(await page.locator('#image-upscale-status').textContent(),/Dropped.png/);assert.equal(await page.evaluate(()=>items.length),0,'Dropping into modal never inserts on original page');
  await page.keyboard.press('Escape');assert.equal(await page.locator('#image-upscale-dialog').isVisible(),false);assert.deepEqual(errors,[]);assert.equal(heavy.length,0,'General enlargement/UI checks never download AI assets');
  console.log('HD UX passed:',width,'sticky primary, empty/drop, device preflight, full-image modes, mouse/touch divider, keyboard, pan/pinch, zoom-sized handle, original isolation');await context.close();
 }
}finally{await browser.close()}
