import fs from 'node:fs';import vm from 'node:vm';import assert from 'node:assert/strict';
const scope=vm.createContext({});
for(const f of ['app/region-fill.js','app/auto-trace.js','app/compound-fill.js','app/paint-layers.js','app/illustration-trace.js','experiments/anime-trace/structure-colors.js','experiments/anime-trace/ink-fill-simplify.js'])vm.runInContext(fs.readFileSync(f,'utf8'),scope);
const {engine,geometry,colors,compound,paint}=vm.runInContext('({engine:AutoTrace,geometry:RegionFill,colors:AnimeStructureColors,compound:CompoundFill,paint:paintSceneItems})',scope);
const rect=(id,x0,y0,x1,y1)=>{const p=[{x:x0,y:y0},{x:x1,y:y0},{x:x1,y:y1},{x:x0,y:y1}];return{...engine.toItem({closed:true},p.map((p,i,a)=>geometry.line(p,a[(i+1)%4])),'#123456',1.2,new Set()),id}};
const width=80,height=70,data=new Uint8Array(width*height*4);
for(let y=0;y<height;y++)for(let x=0;x<width;x++)data.set([...(x>=30&&x<42&&y>=28&&y<42?[30,35,40]:[185,95,60]),255],(y*width+x)*4);
const result={items:[rect('skin',3,3,75,66),rect('earring',30,28,42,42)],issues:[],stats:{paths:2}},saved=JSON.stringify(result),pixels=data.slice();
const colored=colors.run(result,{data,width,height},geometry);
assert.equal(JSON.stringify(result),saved,'Input geometry is immutable');assert.deepEqual(data,pixels,'Reference pixels are immutable');
assert.equal(colored.colorItems.length,2);assert.equal(colored.items,result.items,'Original structural curves are retained, not redrawn');
assert.deepEqual([...colored.colorItems.map(i=>i.fill).sort()],['#1e2328','#b95f3c']);
const samples=it=>colors.curves(it).flatMap(c=>geometry.flatten(c).slice(0,-1));
assert.equal(colored.colorItems.filter(it=>geometry.contains({x:35,y:35},samples(it))).length,1,'Earring has one owning fill, not a skin fill underneath');
const skin=colored.colorItems.find(it=>it.fill==='#b95f3c');assert.equal(compound.recover(skin).length,2,'Native export gets actual separate outer/hole contours');
assert.ok(colored.colorItems.every(it=>it.closed&&it.width===0&&it.fillOpacity===1));
const sourceCurves=paint([...colored.colorItems,...colored.items]).filter(it=>it.paintLayer==='line'||!it.autoTraceColored);
assert.equal(sourceCurves.filter(it=>it.width>0).length,2,'Auto coloring does not introduce additional ink outlines');
assert.equal(JSON.stringify(colors.run(result,{data,width,height},geometry)),JSON.stringify(colored),'Deterministic color selection');
// Nested reflection remains separate and cannot steal the earring color.
const nested=rect('highlight',33,31,37,36);const withHighlight={...result,items:[...result.items,nested]};
const image=data.slice();for(let y=31;y<36;y++)for(let x=33;x<37;x++)image.set([235,230,200,255],(y*width+x)*4);
const out=colors.run(withHighlight,{data:image,width,height},geometry);
assert.equal(out.colorItems.length,3);
for(const p of [{x:10,y:10},{x:40,y:38},{x:35,y:33}])assert.equal(out.colorItems.filter(it=>geometry.contains(p,samples(it))).length,1);
assert.ok(out.colorItems.some(it=>it.fill==='#ebe6c8'),'Small reflection survives instead of global palette merging');
assert.throws(()=>colors.run(result,{data,width:8,height:8},geometry),/aligned/);
const transparent=data.slice();for(let i=3;i<transparent.length;i+=4)transparent[i]=0;
assert.equal(colors.run(result,{data:transparent,width,height},geometry).colorItems.length,0,'Transparent hidden RGB cannot invent fill colors');
console.log('Structural colors: immutable ink, independent nested fills, real holes, local source colors, small highlights, alpha and deterministic output passed.');

// A shadow can exist inside one neural face with NO line crossing it. It must
// still be a separate fill, without promoting any of its boundaries to ink.
const shadow={...rect('shadow',45,14,61,25),fill:'#b96536',fillOpacity:1,width:5,autoTraceColored:true};
const sourceColors={width,height,colorItems:[...colored.colorItems,shadow],items:[rect('unwanted-color-outline',45,14,61,25)]};
const colorSaved=JSON.stringify(sourceColors),hybrid=colors.preserveShading({...result,width,height},sourceColors);
assert.equal(JSON.stringify(sourceColors),colorSaved,'Source segmentation stays immutable');
assert.equal(hybrid.items,result.items,'Ink is exactly the structural input, not source color boundaries');
assert.equal(hybrid.colorItems.length,3,'Unoutlined shading missing from the sketch graph survives');
assert.equal(JSON.stringify(hybrid.colorItems[2].points),JSON.stringify(shadow.points));assert.equal(JSON.stringify(hybrid.colorItems[2].pointHandleAngles),JSON.stringify(shadow.pointHandleAngles));
assert.ok(hybrid.colorItems.every(it=>it.width===0&&it.fillOpacity===1&&it.closed));
assert.equal(paint([...hybrid.colorItems,...hybrid.items]).filter(it=>it.width>0).length,2,'Shadow adds a filled object but no visible stroke');
assert.equal(hybrid.colorItems[2].fill,'#b96536');
hybrid.colorItems[2].fill='#ff00aa';assert.equal(hybrid.colorItems[0].fill,colored.colorItems[0].fill,'Shadow can be recolored independently');
assert.throws(()=>colors.preserveShading({...result,width,height},{...sourceColors,width:79}),/aligned/);
assert.throws(()=>colors.preserveShading({...result,width,height},{...sourceColors,colorItems:[{...shadow,closed:false}]}),/closed/);
const empty=colors.preserveShading({...result,width,height},{width,height,colorItems:[]});assert.equal(empty.colorItems.length,0);
console.log('Source shading: preserves every shadow contour/color, no color-outline network, independent styles and alignment checks passed.');

const {trace,simplifyInk}=vm.runInContext('({trace:IllustrationTrace,simplifyInk:AnimeInkFillSimplify})',scope);
const deps={geometry,compound,trace,engine,colors};
const stroke=engine.toItem({closed:false},[geometry.line({x:10,y:15},{x:65,y:15})],'#182c49',1.25,new Set());
const structural={width,height,items:[stroke]},structuralSaved=JSON.stringify(structural);
const partition=(outline,color='#181820')=>({width,height,...trace.fromSVG(`<svg><path fill="#f5cf9c" d="M0 0L80 0L80 70L0 70Z ${outline}"/><path fill="${color}" d="${outline}"/></svg>`,engine)});
const narrow=partition('M10 14L10 16L65 16L65 14Z'),narrowSaved=JSON.stringify(narrow);
const merged=simplifyInk.run(structural,narrow,deps);
assert.equal(merged.inkSimplification.merged.length,1,'Thin dark ribbon already covered by ink is merged');
assert.equal(merged.colorItems.length,1,'Redundant color object is removed, not just hidden');
assert.equal(merged.colorItems[0].fill.toLowerCase(),'#f5cf9c');
assert.equal(JSON.stringify(structural),structuralSaved,'Existing linework is never moved or redrawn');
assert.equal(JSON.stringify(narrow),narrowSaved,'Source fills are immutable');
assert.equal(JSON.stringify(simplifyInk.run(structural,narrow,deps)),JSON.stringify(merged),'Deterministic union');
for(let y=.5;y<height;y++)for(let x=.5;x<width;x++)assert.equal(merged.colorItems.filter(it=>geometry.contains({x,y},samples(it))).length,1,'Union must leave exactly one owning fill, not a hole or overlap');
const preserve=(name,source,ink=structural)=>{
 const out=simplifyInk.run(ink,source,deps);
 assert.equal(out.inkSimplification.merged.length,0,name);
 assert.equal(JSON.stringify(out.colorItems),JSON.stringify(source.colorItems),name+' preserves all geometry and colors');
};
preserve('A thin mark without supporting ink remains',narrow,{width,height,items:[]});
preserve('Invisible closures are not ink',narrow,{width,height,items:[{...stroke,width:0}]});
preserve('Broad eye shadow remains',partition('M10 9L10 25L65 25L65 9Z','#a0542c'));
preserve('Small solid earring remains',partition('M30 12C28 12 28 18 30 18C32 18 32 12 30 12Z'));
preserve('Thin light highlight remains',partition('M10 14L10 16L65 16L65 14Z','#fffaf0'));
const ring=partition('M10 13L10 17L65 17L65 13Z M12 14L63 14L63 16L12 16Z');
preserve('Thin closed ring retains its hole',ring);
const multi={width,height,...trace.fromSVG('<svg><path fill="#f5cf9c" d="M0 0L80 0L80 70L0 70Z M10 14L10 16L65 16L65 14Z M30 30L30 36L36 36L36 30Z"/><path fill="#181820" d="M10 14L10 16L65 16L65 14Z"/><path fill="#28282f" d="M30 30L36 30L36 36L30 36Z"/></svg>',engine)};
const unedited=multi.colorItems.find(it=>it.fill==='#28282f'),multiOut=simplifyInk.run(structural,multi,deps);
assert.equal(multiOut.inkSimplification.merged.length,1);
assert.ok(multiOut.colorItems.includes(unedited),'Unrelated fills remain the original objects, not rebuilt approximations');
for(let y=.5;y<height;y++)for(let x=.5;x<width;x++)assert.equal(multiOut.colorItems.filter(it=>geometry.contains({x,y},samples(it))).length,1,'Union preserves neighboring holes and independent fill ownership');
assert.throws(()=>simplifyInk.run({...structural,width:79},narrow,deps),/aligned/);
assert.throws(()=>simplifyInk.run({...structural,width:NaN},narrow,deps),/aligned/);
assert.throws(()=>simplifyInk.run(structural,narrow,deps,{maxWidth:20}),/limits/);
assert.throws(()=>simplifyInk.run(structural,{...narrow,colorItems:[{...narrow.colorItems[0],closed:false}]},deps),/closed/);
console.log('Thin ink: supported ribbon union, no gaps/overlap, unchanged ink, shadows/earrings/highlights/rings retained, deterministic and bounded inputs passed.');
