import fs from 'node:fs';import assert from 'node:assert/strict';import {createRequire} from 'node:module';
const {chromium}=createRequire(import.meta.url)('playwright'),browser=await chromium.launch({channel:'chrome',headless:true});
const base=process.env.SKECHU_TEST_URL||'http://127.0.0.1:18782/',out='.codex-tmp/image-upscale-browser';fs.mkdirSync(out,{recursive:true});
const errors=[],requests=[];
const synthetic='<svg xmlns="http://www.w3.org/2000/svg" width="145" height="137"><rect width="145" height="137" fill="#efd7b7"/><path d="M5 90Q70 0 140 95M10 130L135 6" stroke="#12324a" stroke-width="2" fill="none"/><ellipse cx="60" cy="70" rx="15" ry="18" fill="#48a2d8"/><circle cx="60" cy="70" r="7" fill="#173862"/></svg>';
const state=p=>p.evaluate(()=>JSON.stringify(items));
async function setup(p){p.on('pageerror',e=>errors.push(String(e)));p.on('request',r=>requests.push(r.url()));await p.goto(base+'?storage=hd-qa-'+Date.now());await p.waitForFunction(()=>workspaceReady);await p.evaluate(src=>{items=[{id:'hd-ref',type:'image',name:'Synthetic reference',src:'data:image/svg+xml,'+encodeURIComponent(src),x:10,y:20,w:290,h:274,r:0,opacity:.5,referenceOnly:true,preserveFull:true,locked:false}];setOnlySelected('hd-ref');render();fitView()},synthetic)}
async function open(p){await p.locator('#image-upscale').scrollIntoViewIfNeeded();await p.locator('#image-upscale').click();await p.waitForFunction(()=>!document.getElementById('image-upscale-start').disabled)}
async function ready(p){await p.waitForFunction(()=>document.getElementById('image-upscale-dialog').dataset.ready==='true'||(document.getElementById('image-upscale-stop').hidden&&!document.getElementById('image-upscale-start').disabled),{},{timeout:180000});assert.equal(await p.locator('#image-upscale-dialog').getAttribute('data-ready'),'true',await p.locator('#image-upscale-status').textContent())}
const heavy=()=>requests.filter(url=>/tf-4\.22|anime-v3/.test(url));
try{
 const p=await browser.newPage({viewport:{width:1360,height:940}});await setup(p);const before=await state(p);await open(p);assert.equal(heavy().length,0,'Opening the site/dialog must not fetch engine/model');
 await p.keyboard.press('Delete');assert.equal(await state(p),before,'Modal Delete does not delete artwork');await p.locator('#image-upscale-method').selectOption('resize');await p.locator('#image-upscale-start').click();await ready(p);assert.equal(heavy().length,0);assert.equal(await state(p),before);
 await p.locator('#image-upscale-plus').click();assert.equal(await p.locator('#image-upscale-zoom').textContent(),'150%');const box=await p.locator('#image-upscale-svg').boundingBox(),initial=await p.locator('#image-upscale-svg').getAttribute('viewBox');await p.mouse.move(box.x+box.width/2,box.y+box.height/2);await p.mouse.down();await p.mouse.move(box.x+box.width/2+25,box.y+box.height/2+20);await p.mouse.up();assert.notEqual(await p.locator('#image-upscale-svg').getAttribute('viewBox'),initial);
 const download=p.waitForEvent('download');await p.locator('#image-upscale-download').click();const dl=await download;await dl.saveAs(out+'/synthetic-2x.png');assert.equal(dl.suggestedFilename(),'Synthetic reference-hd-2x.png');
 const oldPage=await p.evaluate(()=>activePageId);await p.locator('#image-upscale-apply').click();await p.waitForFunction(id=>activePageId!==id,oldPage);assert.equal(await p.evaluate(id=>JSON.stringify(activeProject().pages.find(page=>page.id===id).items),oldPage),before);const applied=await p.evaluate(async()=>{const ref=items[0],im=new Image();im.src=ref.src;await im.decode();return{w:im.width,h:im.height,locked:ref.locked,opacity:ref.opacity,method:ref.imageEnhancement.method,count:items.length}});assert.deepEqual(applied,{w:290,h:274,locked:false,opacity:.5,method:'resize',count:1});
 // Returning to the original page enables AI and cancellation without mutation.
 await p.evaluate(id=>openPage(id),oldPage);await open(p);await p.locator('#image-upscale-method').selectOption('anime');await p.locator('#image-upscale-start').click();await p.locator('#image-upscale-stop').click();assert.equal(await state(p),before);assert.equal(await p.locator('#image-upscale-apply').isEnabled(),false);
 await p.locator('#image-upscale-start').click();await ready(p);const stats=JSON.parse(await p.locator('#image-upscale-dialog').getAttribute('data-stats'));assert.equal(stats.backend,'webgl');assert.ok(stats.tiles>1&&!stats.tensorLeak);assert.equal(await state(p),before);await p.screenshot({path:out+'/desktop.png'});console.log('Synthetic AI:',JSON.stringify(stats));
 // Cancel after inference has actually begun, not only during model loading.
 await p.locator('#image-upscale-start').click();await p.waitForFunction(()=>document.getElementById('image-upscale-status').textContent.includes('2/4 區塊'),{},{timeout:30000});await p.locator('#image-upscale-stop').click();assert.equal(await p.locator('#image-upscale-dialog').getAttribute('data-ready'),null);assert.equal(await state(p),before);await p.locator('#image-upscale-start').click();await ready(p);
 // Stale image context is rejected even if an outside program edits it.
 await p.evaluate(()=>{items[0].src+=' ';});await p.locator('#image-upscale-apply').click();assert.match(await p.locator('#image-upscale-status').textContent(),/已變更/);await p.locator('#image-upscale-close').click();
 // Private source is optional, never committed, sent to a service, or loaded by normal CI.
 if(process.env.SKECHU_HD_SOURCE){
  await open(p);await p.locator('#image-upscale-file').setInputFiles(process.env.SKECHU_HD_SOURCE);await p.waitForFunction(()=>!document.getElementById('image-upscale-start').disabled&&document.getElementById('image-upscale-status').textContent.includes('640 × 360'));
  await p.locator('#image-upscale-start').click();await ready(p);console.log('Private 640x360 AI:',await p.locator('#image-upscale-dialog').getAttribute('data-stats'));
  const d=p.waitForEvent('download');await p.locator('#image-upscale-download').click();await(await d).saveAs(out+'/private-2x.png');await p.locator('#image-upscale-plus').click();await p.locator('#image-upscale-plus').click();await p.screenshot({path:out+'/private-comparison.png'});await p.locator('#image-upscale-close').click();
 }
 await p.close();
 const context=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true}),mobile=await context.newPage();await setup(mobile);await open(mobile);const mobileBefore=await state(mobile);
 assert.ok(await mobile.evaluate(()=>document.getElementById('image-upscale-dialog').getBoundingClientRect().right<=innerWidth));await mobile.locator('#image-upscale-method').selectOption('resize');await mobile.locator('#image-upscale-start').tap();await ready(mobile);await mobile.locator('#image-upscale-plus').tap();
 // Real Chromium touch events, two-finger zoom (not emulated mouse drag).
 const cdp=await context.newCDPSession(mobile),r=await mobile.locator('#image-upscale-svg').boundingBox(),cx=r.x+r.width/2,cy=r.y+100;
 await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:cx-35,y:cy,id:1},{x:cx+35,y:cy,id:2}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:cx-60,y:cy,id:1},{x:cx+60,y:cy,id:2}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});assert.ok(parseInt(await mobile.locator('#image-upscale-zoom').textContent())>180);
 await mobile.locator('#image-upscale-apply').scrollIntoViewIfNeeded();assert.ok(await mobile.locator('#image-upscale-apply').evaluate(el=>el.getBoundingClientRect().width>=125&&el.getBoundingClientRect().height<=60),'Mobile action must not collapse into vertical text');await mobile.screenshot({path:out+'/mobile.png'});await mobile.locator('#image-upscale-close').tap();assert.equal(await state(mobile),mobileBefore);await context.close();assert.deepEqual(errors,[]);
 console.log('Image HD UI OK: lazy loading, real Worker WebGL, cancellation, isolated keyboard, comparison/pan/zoom, PNG, preserved original/new unlocked page, stale guard, mobile controls and touch pinch.');
}finally{await browser.close()}
