import fs from 'node:fs';
import vm from 'node:vm';
import assert from 'node:assert/strict';
const html=fs.readFileSync(new URL('../app/index.html',import.meta.url),'utf8');
const css=fs.readFileSync(new URL('../app/theme-controls.css',import.meta.url),'utf8');
const source=fs.readFileSync(new URL('../app/theme-controls.js',import.meta.url),'utf8');
const stored=new Map([['skechu-ui-theme','linen']]),events=new Map();
const buttons=['graphite','mist','linen'].map(theme=>({dataset:{uiTheme:theme},active:false,classList:{toggle(name,value){if(name==='active')this.owner.active=value}},setAttribute(name,value){this[name]=value}}));buttons.forEach(button=>button.classList.owner=button);
const picker={addEventListener(type,fn){events.set(type,fn)}},meta={content:''};
const document={documentElement:{dataset:{}},getElementById:id=>id==='theme-switcher'?picker:null,querySelectorAll:selector=>selector==='[data-ui-theme]'?buttons:[],querySelector:selector=>selector==='meta[name="theme-color"]'?meta:null,addEventListener(){}};
const localStorage={getItem:key=>stored.get(key)||null,setItem:(key,value)=>stored.set(key,value)};
const ctx=vm.createContext({document,localStorage});vm.runInContext(source,ctx);ctx.initializeThemeControls();
assert.equal(document.documentElement.dataset.theme,'linen');assert.equal(buttons[2].active,true);assert.equal(meta.content,'#e9e4db');
events.get('click')({target:{closest:()=>buttons[1]}});assert.equal(stored.get('skechu-ui-theme'),'mist');assert.equal(meta.content,'#eceef1');assert.equal(buttons[1].active,true);
ctx.applySkechuTheme('invalid');assert.equal(document.documentElement.dataset.theme,'graphite','Unknown themes safely fall back to graphite');
for(const theme of ['graphite','mist','linen']){assert.ok(css.includes(`[data-theme="${theme}"]`));assert.ok(html.includes(`data-ui-theme="${theme}"`))}
for(const marker of ['--surface','--canvas-desk','--glass-surface','--range-track','.stage-shell{position:relative','data-ui-theme="graphite"','theme-controls.js?v=46-canvas-shapes','theme-controls.css?v=47-grid-sync','fill-opacity:.3','.action-menu-popover{position:fixed','input[type="range"]::-webkit-slider-runnable-track','grid-template-rows:48px minmax(0,1fr) 62px'])assert.ok(css.includes(marker)||html.includes(marker),'Missing theme marker '+marker);
for(const marker of ['class="sr-only">複製到 PPT','class="action-menu export-menu"','class="action-menu workspace-menu"','class="tool-icon magnet-icon"','opacity:.3,locked:true,referenceOnly:true','preserveAspectRatio="xMidYMid meet"','function renderCanvasGrid()'])assert.ok(html.includes(marker),'Missing compact interface marker '+marker);
assert.ok(html.includes('class="page-settings-icon"'),'Workspace menu must use a page settings icon, not a sun-like gear');
assert.ok(html.includes('class="project-files-icon"'),'Export menu must use a project files icon, not a hamburger');
assert.ok(html.includes('M13 4h7v7M20 4l-9 9'),'Export icon must use a clear outward share arrow');
assert.ok(css.includes('.projectbar:has(.export-menu[open]){overflow:visible}'),'Open export menu must escape project bar clipping');
assert.ok(!html.includes('M12 3.5v2M12 18.5v2'),'Sun-like workspace menu icon must be removed');
assert.ok(!html.includes('M5 7h14M5 12h14M5 17h14'),'Hamburger export icon must be removed');
assert.ok(!css.includes('repeating-linear-gradient'),'Canvas glass must not use diagonal line bands');
assert.ok(!css.includes('radial-gradient(circle at 1px 1px'),'Canvas surface must not use a dotted texture');
assert.ok(html.includes('const CANVAS_GRID_STEP=20')&&html.includes("stageWrap.style.setProperty('--checker-cell'")&&css.includes('--checker-tile:24px'),'The checkerboard must share the SVG grid step and canvas origin');
assert.ok(css.includes('background-attachment:local,local,local,local'),'The checkerboard must remain aligned while the canvas scrolls');
assert.ok(css.includes('.stage-shell{position:relative;isolation:isolate;overflow:visible'),'Objects outside the canvas must not be clipped by the glass shell');
assert.ok(html.includes('.stage{width:100%;height:auto;display:block;overflow:visible'),'SVG overflow must stay visible and interactive');
assert.ok(!html.includes('描圖筆：點一下放錨點'),'The inspector must not contain a permanent shortcut manual');
assert.ok(!html.includes('class="palette-tip"'),'Obvious paint instructions must not consume sidebar space');
assert.ok(source.includes("menu.classList.contains('workspace-menu')"),'Workspace menu must prefer opening beside the trigger');
assert.match(html,/id="trace-source-tools"[\s\S]*?id="import-reference"/,'Reference import must have its own auto-trace source group');
assert.ok(html.includes('id="add-shape"')&&html.includes('aria-controls="shape-menu-popover"'),'Shape button must control an independent floating menu');
assert.match(html,/id="shape-menu-popover"[\s\S]*?data-shape-kind="rectangle"[\s\S]*?data-shape-kind="ellipse"[\s\S]*?data-shape-kind="polygon"/,'Shape menu must offer three icon choices');
assert.ok(!html.includes('id="shape-kind"'),'Shape type selector must remain hidden until the shape button is opened');
assert.ok(html.includes('<span class="tool-text">新增底圖</span>'),'Reference toolbar label must say 新增底圖');
for(const id of ['canvas-width','canvas-height'])assert.ok(html.includes(`id="${id}"`),'Missing canvas dimension control '+id);
assert.ok(html.includes('function updateCanvasSize()')&&html.includes('page.canvasWidth=width;page.canvasHeight=height'),'Canvas dimensions must update the active page model');
assert.ok(source.includes("shapePopover.hidden=!opening")&&source.includes('requestAnimationFrame(positionShapeMenu)'),'Shape menu must escape toolbar clipping through a separately positioned overlay');
assert.ok(!html.includes('width=Math.max(320'),'Reference image width must never be independently stretched');
console.log('Interface themes OK: responsive shape menu, editable canvas size, unclipped objects and clean glass canvas.');
