import fs from 'node:fs';import assert from 'node:assert/strict';import {createRequire} from 'node:module';
const {chromium}=createRequire(import.meta.url)('playwright'),browser=await chromium.launch({channel:'chrome',headless:true}),base=process.env.SKECHU_TEST_URL||'http://127.0.0.1:18782/',out='.codex-tmp/native-fill-browser';fs.mkdirSync(out,{recursive:true});const errors=[];
const source='<svg xmlns="http://www.w3.org/2000/svg" width="140" height="100"><defs><linearGradient id="a"><stop stop-color="#123454"/><stop offset="1" stop-color="#7cacd8"/></linearGradient><radialGradient id="b"><stop stop-color="#e2f7ff"/><stop offset=".3" stop-color="#46a2e8"/><stop offset="1" stop-color="#294167"/></radialGradient></defs><rect width="140" height="100" fill="url(#a)"/><ellipse cx="75" cy="45" rx="29" ry="34" fill="url(#b)"/></svg>';
const snapshot=p=>p.evaluate(()=>JSON.stringify(items,(k,v)=>k==='attachments'&&v&&Object.keys(v).length===0?undefined:v));
async function ready(p){await p.waitForFunction(()=>autoTraceResult&&!document.getElementById('auto-trace-apply').disabled&&!autoTraceDialogMotion,null,{timeout:90000})}
async function setup(p){p.on('pageerror',e=>errors.push(String(e)));await p.goto(base+'?v=88-detail-fill&storage=native-fill-'+Date.now());await p.waitForFunction(()=>workspaceReady);await p.evaluate(src=>{items=[{id:'native-ref',type:'image',name:'Synthetic light',src:'data:image/svg+xml,'+encodeURIComponent(src),x:40,y:20,w:420,h:300,r:0,opacity:.5,locked:false,referenceOnly:true,preserveFull:true}];setOnlySelected('native-ref');render();fitView()},source);await p.locator('#auto-fill').scrollIntoViewIfNeeded();await p.locator('#auto-fill').click();await p.locator('#auto-trace-mode').selectOption('native2d');await ready(p)}
try{const p=await browser.newPage({viewport:{width:1400,height:1000}});await setup(p);const original=await p.evaluate(()=>JSON.stringify(items));
 assert.deepEqual(await p.locator('#auto-trace-mode option').evaluateAll(os=>os.map(o=>o.value)),['fill-auto','illustration','gradient','native2d']);assert.match(await p.locator('#auto-trace-mode-hint').textContent(),/不是單一物件/);assert.equal(await p.locator('#auto-trace-lines image').count(),0);assert.ok(await p.locator('#auto-trace-lines linearGradient').count()>0);assert.ok(await p.evaluate(()=>autoTraceResult.stats.shading.multiAngle&&autoTraceResult.stats.shading.precise));assert.equal(await p.locator('#auto-trace-lines [data-coverage-normalized]').count(),1);
 const preview=await p.evaluate(()=>activeAutoTraceResult().items.map(it=>it.fillGradient||null));await p.screenshot({path:out+'/preview.png'});await p.locator('#auto-trace-apply').click();await p.waitForFunction(()=>!autoTraceDialog.open&&items.length>1);assert.equal(await p.evaluate(()=>JSON.stringify(items.filter(it=>!it.autoTraceColored))),original);assert.deepEqual(await p.evaluate(()=>items.filter(it=>it.autoTraceColored).map(it=>it.fillGradient||null)),preview);
 const exported=await p.evaluate(async()=>{const fills=items.filter(it=>it.autoTraceColored);selectedIds=new Set(fills.map(it=>it.id));selected=fills[0].id;const svg=await selectionSvgBlob(),doc=new DOMParser().parseFromString(await svg.blob.text(),'image/svg+xml');return{body:JSON.parse(nativeBody(fills)),images:doc.querySelectorAll('image').length,gradients:doc.querySelectorAll('linearGradient').length,closed:fills.every(it=>it.closed&&it.width===0&&!it.src&&!it.fillPicture)}});assert.equal(exported.images,0);assert.ok(exported.gradients>0&&exported.closed);assert.ok(exported.body.items.some(it=>it.fillGradient?.type==='linear'));fs.writeFileSync(out+'/native-payload.json',JSON.stringify(exported.body));
 const filled=await snapshot(p);await p.keyboard.press('Control+z');assert.equal(await snapshot(p),original);await p.keyboard.press('Control+Shift+z');assert.equal(await snapshot(p),filled);
 await p.evaluate(()=>{const it=items.find(it=>it.fillGradient);setOnlySelected(it.id);commit();it.fillGradient.angle=137;it.fillGradient.stops[0].color='#ff1188';render()});assert.ok(await p.evaluate(()=>byId(selected).fillGradient.angle===137));await p.keyboard.press('Control+z');assert.equal(await snapshot(p),filled);await p.evaluate(()=>writeWorkspace(workspacePayload()));await p.reload();await p.waitForFunction(()=>workspaceReady);assert.equal(await snapshot(p),filled);
 await p.close();const c=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true}),mobile=await c.newPage();await setup(mobile);await mobile.locator('#auto-trace-apply').scrollIntoViewIfNeeded();await mobile.screenshot({path:out+'/mobile.png'});await mobile.locator('#auto-trace-apply').tap();await mobile.waitForFunction(()=>!autoTraceDialog.open&&items.some(it=>it.fillGradient));assert.ok(await mobile.evaluate(()=>items.filter(it=>it.autoTraceColored).every(it=>it.type==='arrow'&&!it.src)));await c.close();assert.deepEqual(errors,[]);console.log('Native multi-direction fill OK: usable desktop/mobile Apply, only editable vectors/linear stops, no bitmap fallback, preview parity, native payload, Undo/Redo, recolor and persistence.');
}finally{await browser.close()}
