import fs from 'node:fs';import assert from 'node:assert/strict';import {createRequire} from 'node:module';
const {chromium}=createRequire(import.meta.url)('playwright'),browser=await chromium.launch({channel:'chrome',headless:true});
const base=process.env.SKECHU_TEST_URL||'http://127.0.0.1:18782/',out='.codex-tmp/source-gradient-browser';fs.mkdirSync(out,{recursive:true});
const source='<svg xmlns="http://www.w3.org/2000/svg" width="320" height="240"><defs><linearGradient id="b"><stop stop-color="#19295e"/><stop offset="1" stop-color="#68cfe4"/></linearGradient><linearGradient id="f" x2=".4" y2="1"><stop stop-color="#ab715d"/><stop offset="1" stop-color="#ebbc85"/></linearGradient><linearGradient id="e" x2="0" y2="1"><stop stop-color="#518fd1"/><stop offset="1" stop-color="#202b5b"/></linearGradient></defs><path d="M0 0H320V240H0Z" fill="url(#b)"/><path d="M80 30Q160 0 240 30L230 165Q200 210 160 227Q115 207 90 165Z" fill="url(#f)"/><ellipse cx="120" cy="105" rx="32" ry="36" fill="url(#e)"/><ellipse cx="200" cy="105" rx="32" ry="36" fill="url(#e)"/><circle cx="120" cy="105" r="10" fill="#13243e"/><circle cx="200" cy="105" r="10" fill="#13243e"/><circle cx="116" cy="101" r="3" fill="white"/><circle cx="196" cy="101" r="3" fill="white"/></svg>';
const errors=[];
async function setup(page){page.on('pageerror',e=>errors.push(String(e)));await page.goto(base+'?storage=source-gradient-ui-'+Date.now());await page.waitForFunction(()=>workspaceReady);await page.evaluate(source=>{resetEditorState();activePage().canvasWidth=640;activePage().canvasHeight=480;items=[{id:'source',type:'image',name:'Local synthetic shading',src:'data:image/svg+xml,'+encodeURIComponent(source),x:40,y:30,w:560,h:420,r:0,opacity:.5,referenceOnly:true,preserveFull:true,locked:false},{id:'keep-ink',type:'arrow',name:'Original ink',points:[{x:50,y:440},{x:250,y:430}],color:'#123f8c',width:2,closed:false,curved:false,fillOpacity:0,endHead:false}];setOnlySelected('source');setCanvasAppearance('#ffffff',1);render();fitView()},source)}
async function ready(p){const started=Date.now();console.log('Waiting for preview: '+await p.locator('#auto-trace-mode').inputValue());try{await p.waitForFunction(()=>document.getElementById('auto-trace-svg').getAttribute('aria-busy')==='false'&&!autoTraceDialogMotion,{},{timeout:180000})}catch(error){throw Error(error.message+'; '+await p.locator('#auto-trace-summary').textContent())}console.log('Preview ready in '+(Date.now()-started)+' ms: '+await p.locator('#auto-trace-summary').textContent());assert.ok(await p.evaluate(()=>autoTraceResult&&!document.getElementById('auto-trace-apply').disabled),await p.locator('#auto-trace-summary').textContent());await p.evaluate(()=>Promise.all(autoTraceDialog.getAnimations({subtree:true}).filter(a=>Number.isFinite(a.effect?.getComputedTiming().endTime)).map(a=>a.finished.catch(()=>{}))))}
const state=p=>p.evaluate(()=>JSON.stringify(items));
try{
 const page=await browser.newPage({viewport:{width:1500,height:1000}});await setup(page);const before=await state(page);await page.locator('#auto-fill').click();await ready(page);
 assert.deepEqual(await page.locator('#auto-trace-mode option').evaluateAll(options=>options.map(o=>o.value)),['fill-auto','illustration','gradient','native2d']);assert.ok(await page.locator('#auto-trace-mode').isEnabled());
 assert.equal(await page.evaluate(()=>autoTraceResult.stats.fillRecommendation.chosen),'native2d');assert.match(await page.locator('#auto-trace-mode-hint').textContent(),/推薦「精細原生漸層」/);assert.ok(await page.locator('#auto-trace-lines linearGradient').count()>0);assert.equal(await state(page),before);assert.equal(await page.locator('#auto-trace-show-anchors').isChecked(),false);
 await page.screenshot({path:out+'/desktop-recommendation.png'});
 await page.locator('#auto-trace-mode').selectOption('illustration');await ready(page);assert.equal(await page.locator('#auto-trace-lines linearGradient').count(),0);assert.equal(await state(page),before);
 // Burst changes must leave only the final gradient job.
 await page.locator('#auto-trace-mode').selectOption('gradient');await page.locator('#auto-trace-mode').selectOption('illustration');await page.locator('#auto-trace-mode').selectOption('gradient');await ready(page);assert.ok(await page.locator('#auto-trace-lines linearGradient').count()>0);
 const preview=await page.evaluate(()=>activeAutoTraceResult().items.map(it=>it.fillGradient||null));await page.locator('#auto-trace-apply').click();await page.waitForFunction(()=>!autoTraceDialog.open&&items.some(it=>it.autoTraceColored));
 assert.equal(await page.evaluate(()=>JSON.stringify(items.filter(it=>!it.autoTraceColored))),before);assert.deepEqual(await page.evaluate(()=>items.filter(it=>it.autoTraceColored).map(it=>it.fillGradient||null)),preview);assert.ok(await page.evaluate(()=>items.filter(it=>it.autoTraceColored).every(it=>it.width===0&&it.closed)));
 // A legacy line-width migration must never add outlines to automatic fills.
 assert.ok(await page.locator('#scene [data-gradient-partition]').count()>0,'Applied gradients retain isolated shared-edge coverage');
 const exported=await page.evaluate(async()=>{const fills=items.filter(it=>it.autoTraceColored);selectedIds=new Set(fills.map(it=>it.id));selected=fills[0].id;const full=await selectionSvgBlob(),doc=new DOMParser().parseFromString(await full.blob.text(),'image/svg+xml'),count=doc.querySelectorAll('.arrow-line').length,gradients=doc.querySelectorAll('linearGradient').length;const chosen=fills.find(it=>it.fillGradient);setOnlySelected(chosen.id);const single=await selectionSvgBlob(),one=new DOMParser().parseFromString(await single.blob.text(),'image/svg+xml');const before=chosen.points[0].x;chosen.points[0].x+=10;const detached=GradientRegions.coverageKey(chosen)===null;chosen.points[0].x=before;return{count,expected:fills.length,gradients,single:one.querySelectorAll('.arrow-line').length,singleGradient:one.querySelectorAll('linearGradient').length,detached}});
 assert.equal(exported.count,exported.expected,'Nested coverage groups must not disappear from selection SVG');assert.ok(exported.gradients>0&&exported.single===1&&exported.singleGradient===1&&exported.detached,'Single-object export, stops and geometry detachment are preserved');
 await page.evaluate(()=>{activePage().items=items;migrateTraceStrokeWidths();render()});assert.ok(await page.evaluate(()=>items.filter(it=>it.autoTraceColored).every(it=>it.width===0)));
 const filled=await state(page);await page.keyboard.press('Control+z');assert.equal(await state(page),before);await page.keyboard.press('Control+Shift+z');assert.equal(await state(page),filled);
 await page.evaluate(()=>{const it=items.find(it=>it.fillGradient);setOnlySelected(it.id);commit();applyColorToItem(it,'#ff3388',true);render()});assert.ok(await page.evaluate(()=>byId(selected).fill==='#ff3388'&&!byId(selected).fillGradient));await page.keyboard.press('Control+z');assert.equal(await state(page),filled);
 await page.evaluate(()=>writeWorkspace(workspacePayload()));await page.reload();await page.waitForFunction(()=>workspaceReady);assert.ok(await page.evaluate(()=>items.some(it=>it.fillGradient)&&items.filter(it=>it.autoTraceColored).every(it=>it.width===0)),'Reload preserves fills without legacy outlines');
 // Packaged HTTP fallback worker loads the same gradient engine.
 assert.ok(await page.locator('#scene [data-gradient-partition]').count()>0,'Reload preserves shared-edge coverage');
 const workerResult=await page.evaluate(async()=>{const im=new Image();im.src=items.find(it=>it.type==='image').src;await im.decode();const c=document.createElement('canvas');c.width=320;c.height=240;const g=c.getContext('2d');g.drawImage(im,0,0);const data=g.getImageData(0,0,320,240).data,vectorWasm=await IllustrationTrace.wasmBytes();return await new Promise((resolve,reject)=>{const worker=new Worker('auto-trace-worker.js?v=84-gradient-fields');worker.onerror=e=>{worker.terminate();reject(Error(e.message))};worker.onmessage=e=>{if(e.data.type==='progress')return;worker.terminate();resolve(e.data)};worker.postMessage({width:320,height:240,data,vectorWasm,options:{mode:'gradient'}})})});assert.equal(workerResult.type,'result');assert.ok(workerResult.result.colorItems.some(it=>it.fillGradient));await page.close();
 const context=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true}),mobile=await context.newPage();await setup(mobile);const mobileBefore=await state(mobile);await mobile.locator('#auto-fill').scrollIntoViewIfNeeded();await mobile.locator('#auto-fill').tap();await ready(mobile);assert.ok(await mobile.locator('#auto-trace-mode').isEnabled());assert.ok(await mobile.locator('#auto-trace-lines linearGradient').count()>0);assert.equal(await mobile.locator('#auto-trace-advanced').getAttribute('open'),null);await mobile.screenshot({path:out+'/mobile-recommendation.png'});await mobile.locator('#auto-trace-advanced summary').tap();assert.ok(await mobile.locator('#auto-trace-threshold').isVisible());await mobile.locator('#auto-trace-advanced summary').tap();await mobile.locator('#auto-trace-cancel').tap();await mobile.waitForFunction(()=>!autoTraceDialog.open);assert.equal(await state(mobile),mobileBefore);
 const apiResult=await mobile.evaluate(async()=>{const before=JSON.stringify(items),controller=new AbortController(),result=await runAutomationTrace(items.find(it=>it.type==='image'),{mode:'gradient',threshold:120,accuracy:3.5,simplify:90,minLength:5},controller.signal,()=>{});return{unchanged:JSON.stringify(items)===before,allFills:result.items.every(it=>it.autoTraceColored&&it.closed&&it.width===0),gradients:result.items.filter(it=>it.fillGradient).length}});assert.ok(apiResult.unchanged&&apiResult.allFills&&apiResult.gradients>0,'Automation stages source-gradient fills without mutating the page');await context.close();
 assert.deepEqual(errors,[]);console.log('Source-gradient UI OK: smart recommendation, 3 modes, real Blob/HTTP workers, coalescing, preview/apply parity, independent fills, recolor, Undo/Redo, save/reload without outlines, and mobile cancel.');
}finally{await browser.close()}
