import assert from 'node:assert/strict';import{createRequire}from'node:module';const{chromium}=createRequire(import.meta.url)('playwright');
const browser=await chromium.launch({channel:'chrome',headless:true});
try{const page=await browser.newPage();await page.goto((process.env.SKECHU_TEST_URL||'http://127.0.0.1:18782/')+'?storage=coverage-test-'+Date.now());await page.waitForFunction(()=>workspaceReady);
 const result=await page.evaluate(async()=>{
  const line=(p,q)=>({p0:p,c1:{x:(2*p.x+q.x)/3,y:(2*p.y+q.y)/3},c2:{x:(p.x+2*q.x)/3,y:(p.y+2*q.y)/3},p3:q}),p=(x,y)=>({x,y}),a=p(0,0),b=p(140,0),c=p(140,100),d=p(0,100),u=p(27.2,0),v=p(109.6,100),curve={p0:u,c1:p(102,19),c2:p(30,69),p3:v},reverse={p0:v,c1:curve.c2,c2:curve.c1,p3:u};
  const fills=[[line(a,u),curve,line(v,d),line(d,a)],[line(u,b),line(b,c),line(c,v),reverse]].map((cs,i)=>{const it=AutoTrace.toItem({closed:true},cs,'#508ca4',0,new Set());Object.assign(it,{id:'coverage-'+i,fill:'#508ca4',fillOpacity:1,autoTraceColored:true,layerGroup:{id:'coverage',name:'Coverage'}});GradientRegions.stamp(it,'coverage');it.fillPartition.count=2;it.fillPartition.frame=[a,b,c,d];return it});
  const render=async(list,width=140,height=100)=>{const markup=sceneMarkup(list,'coverage-proof'),im=new Image();im.src='data:image/svg+xml,'+encodeURIComponent(`<svg xmlns="http://www.w3.org/2000/svg" width="${width}" height="${height}"><style>.arrow-hit{fill:none;stroke:none}</style>${markup}</svg>`);await im.decode();const canvas=document.createElement('canvas');canvas.width=width;canvas.height=height;const cx=canvas.getContext('2d');cx.drawImage(im,0,0);return{data:cx.getImageData(0,0,width,height).data,markup}};
  const full=await render(fills);let holes=0,maxColorError=0;for(let i=0;i<full.data.length;i+=4){if(full.data[i+3]!==255)holes++;for(let c=0;c<3;c++)maxColorError=Math.max(maxColorError,Math.abs(full.data[i+c]-[80,140,164][c]))}
  const partial=await render(fills.slice(0,1)),hidden=await render([fills[0],{...fills[1],hidden:true}]);
  const ref={x:50,y:40,w:140,h:100,r:31},transformed=transformAutoTraceItems({items:fills,issues:[]},ref,140,100,'rotated',(()=>{let i=0;return()=>String(i++)})());
  const rotated=await render(transformed,240,180),f=GradientRegions.coverageFrame(transformed[0]);let outside=false;for(const [x,y] of [[0,0],[239,0],[0,179],[239,179]])if(rotated.data[(y*240+x)*4+3])outside=true;
  return{holes,maxColorError,fullNormalized:full.markup.includes('data-coverage-normalized'),partialNormalized:partial.markup.includes('data-coverage-normalized'),hiddenNormalized:hidden.markup.includes('data-coverage-normalized'),partialHoles:partial.data.some((v,i)=>i%4===3&&v===0),frameRotated:f.points[0].x!==50&&f.points[0].y!==40,rotatedNormalized:rotated.markup.includes('data-coverage-normalized'),outside};
 });
 assert.equal(result.holes,0,'A complete uniform partition must remain opaque at every seam');assert.ok(result.maxColorError<=3,'Antialias seams must not brighten or darken a uniform fill');assert.ok(result.fullNormalized&&result.partialHoles&&!result.partialNormalized&&!result.hiddenNormalized);assert.ok(result.frameRotated&&result.rotatedNormalized&&!result.outside,'Coverage clip follows the same rotation/translation as native geometry');console.log('Fill coverage: '+JSON.stringify(result));
}finally{await browser.close()}
